trigger:
- '*'
pool:
  name: Windows DGO PC
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'
    arguments: '--no-restore --configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--no-build --configuration Release'

- task: WhiteSource Bolt@21
  displayName: 'Run WhiteSource Bolt'